name: app_curso_manguinho
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: 0.12.2
  provider: 4.3.2+3
  equatable: 1.2.5
  get: 3.4.2
  flutter_secure_storage: 3.3.5
  carousel_slider: 2.3.1
  intl: 0.16.1
  localstorage: 3.0.6+9

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: 1.15.0
  mockito: 3.0.2
  faker: 1.3.0
  flutter_launcher_icons: 0.7.5

flutter:
  uses-material-design: true
  assets:
    - lib/ui/assets/
    
flutter_icons:
  ios: true
  android: true
  image_path_android: lib/ui/assets/icons/android.png
  image_path_ios: lib/ui/assets/icons/ios.png
  adaptative_icon_background: lib/ui/assets/icons/background.png
  adaptative_icon_foreground: lib/ui/assets/icons/foreground.png
